openapi: 3.0.3
info:
  title: PureStaff
  description: |-
    Обращаемся get /init-as-company - видим форму заполнения о вакансии.
    Жмем на кнопку "отправить" - в ответ получаем в заголовках vacancy_id , который отправляем с каждым запросом, get /staff получаем анкеты - листаем - при желании лайкаем - отсылается get /result - можем получить совпадение - тогда красивое окно поздравления

  termsOfService: http://swagger.io/terms/
  contact:
    email: vladimir.konstantinov@simbirsoft.com
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: vacancy
    description: Operations about vacancy
paths:
  /init-as-staff:
    get:
      tags:
        - start
      summary: get empty staff form
      responses:
        '200':
          description: for
          content:
            text/html:
              schema:
                type: string
                format: binary
                example: '<!doctype html><html><head><title>webpage!</title></head><body><p>This.</p></body></html>'
        '400':
          description: Invalid
    put:
      tags:
        - start
      summary: insert new staff
      operationId: insertStaff
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStaffRequest'
      responses:
        '200':
          description: successful operation
          headers:
            staff_id:
              schema:
                type: string
                example: 64ee562b4606600ca8d6c752
              description: NEED SAFE for matchig requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateStaffResponse'
        '400':
          description: Invalid
  /vacancy:
    get:
      tags:
        - staff
      summary: get vacancy list (?page=0&size=5)
      operationId: getVacancyList
      parameters:
        - name: page
          in: query
          description: 'miss page vacancy'
          required: false
          schema:
            type: integer
            example: 0
        - name: size
          in: query
          description: 'amount vacancy'
          required: false
          schema:
            type: integer
            example: 5
        - name: specialization
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/specialization'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVacancyListResponse'
        '400':
          description: Invalid
        '404':
          description: Vacancy not found
  /result-with-vacancy:
    get:
      tags:
        - result
      summary: get the result of match
      operationId: getMatch
      parameters:
        - name: vacancy_id
          in: query
          description: 'staff'
          required: true
          schema:
            type: string
            example: 64ee562b4606600ca8d6c752
        - name: staff_id
          in: header
          description: 'vacancy'
          required: true
          schema:
            type: string
            example: 64ee562b4606600ca8d6c752
      responses:
        '200':
          description: if Yes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateVacancyResponse'
        '202':
          description: if No
components:
  schemas:
    specialization:
      type: string
      enum:
        - Back
        - Front
    CreateStaffRequest:
      type: object
      properties:
        name:
          type: string
          example: Bob
        specialization:
          type: string
          schema:
          $ref: '#/components/schemas/specialization'
        aboutMe:
          type: string
          example: Hi, i'm excelent boy; Free to work
        photo:
          type: string
          description: 'The path to the alredy uploaded image'
          example: mnt/staff/{id}/1.jpg
    CreateStaffResponse:
      type: object
      properties:
        name:
          type: string
          example: Bob
        specialization:
          type: string
          schema:
          $ref: '#/components/schemas/specialization'
        aboutMe:
          type: string
          example: Hi, i'm excelent boy; Free to work
        photo:
          type: string
          description: 'The path to the alredy uploaded image'
          example: mnt/staff/{id}/1.jpg
        staff_id:
          type: string
          example: 64ee562b4606600ca8d6c752
        rating:
          type: number
          format: double
          example: 5.0
    GetStaffListResponse:
      type: object
      properties:
        staff:
          type: array
          items:
            $ref: '#/components/schemas/CreateStaffResponse'
        page:
          type: object
          properties:
            size:
              type: integer
              format: int32
              example: 2
            totalElements:
              type: integer
              format: int32
              example: 2
            totalPages:
              type: integer
              format: int32
              example: 1
            number:
              type: integer
              format: int32
              example: 0

    CreateVacancyRequest:
      type: object
      properties:
        company_name:
          type: string
          example: Intel
        photo:
          type: string
          description: 'The path to the alredy uploaded image'
          example: mnt/staff/{id}/1.jpg
        job_title:
          type: string
          example: Need senior BackEnd developer
        specialization:
          type: string
          schema:
          $ref: '#/components/schemas/specialization'
        requirements:
          type: array
          items:
            type: string
          example: ["Java 11", "Spring", "Docker"]
        pay_fork:
          type: integer
          format: int32
          example: 100000
    CreateVacancyResponse:
      type: object
      properties:
        company_name:
          type: string
          example: Intel
        photo:
          type: string
          description: 'The path to the alredy uploaded image'
          example: mnt/staff/{id}/1.jpg
        job_title:
          type: string
          example: Need senior BackEnd developer
        specialization:
          type: string
          schema:
          $ref: '#/components/schemas/specialization'
        requirements:
          type: array
          items:
            type: string
          example: ["Java 11", "Spring", "Docker"]
        pay_fork:
          type: integer
          format: int32
          example: 100000
        vacancy_id:
          type: string
          example: 64ee562b4606600ca8d6c752
        rating:
          type: number
          format: double
          example: 5.0
    GetVacancyListResponse:
      type: object
      properties:
        vacancy:
          type: array
          items:
            $ref: '#/components/schemas/CreateVacancyResponse'
        page:
          type: object
          properties:
            size:
              type: integer
              format: int32
              example: 2
            totalElements:
              type: integer
              format: int32
              example: 2
            totalPages:
              type: integer
              format: int32
              example: 1
            number:
              type: integer
              format: int32
              example: 0

    CreateVacancyResponse2:
      type: object
      properties:
        company_name:
          type: string
          example: Intel
        photo:
          type: string
          description: 'The path to the alredy uploaded image'
          example: mnt/staff/{id}/1.jpg
        job_title:
          type: string
          example: Need senior BackEnd developer
        specialization:
          type: string
          schema:
          $ref: '#/components/schemas/specialization'
        requirements:
          type: array
          items:
            type: string
          example: ["Java 11", "Spring", "Docker"]
        pay_fork:
          type: integer
          format: int32
          example: 100000
        vacancy_id:
          type: string
          example: 64ee562b4606600ca8d6c752
        rating:
          type: number
          format: double
          example: 5.0
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  example: http://localhost:8080/vacancy/64ee562b4606600ca8d6c752
            vacancy:
              type: object
              properties:
                href:
                  type: string
                  example: http://localhost:8080/vacancy/64ee562b4606600ca8d6c752
    GetVacancyListResponce2:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            vacancy:
              type: array
              items:
                $ref: '#/components/schemas/CreateVacancyResponse'
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  example: http://localhost:8080/vacancy?page=0&size=20
            profile:
              type: object
              properties:
                href:
                  type: string
                  example: http://localhost:8080/profile/vacancy
        page:
          type: object
          properties:
            size:
              type: integer
              format: int32
              example: 2
            totalElements:
              type: integer
              format: int32
              example: 2
            totalPages:
              type: integer
              format: int32
              example: 1
            number:
              type: integer
              format: int32
              example: 0
    CreateStaffResponse2:
      type: object
      properties:
        name:
          type: string
          example: Bob
        specialization:
          type: string
          schema:
          $ref: '#/components/schemas/specialization'
        aboutMe:
          type: string
          example: Hi, i'm excelent boy; Free to work
        photo:
          type: string
          description: 'The path to the alredy uploaded image'
          example: mnt/staff/{id}/1.jpg
        staff_id:
          type: string
          example: 64ee562b4606600ca8d6c752
        rating:
          type: number
          format: double
          example: 5.0
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  example: http://localhost:8080/staff/64ee562b4606600ca8d6c752
            staff:
              type: object
              properties:
                href:
                  type: string
                  example: http://localhost:8080/staff/64ee562b4606600ca8d6c752
    GetStaffListResponse2:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            staff:
              type: array
              items:
                $ref: '#/components/schemas/CreateStaffResponse'
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  example: http://localhost:8080/staff?page=0&size=20
            profile:
              type: object
              properties:
                href:
                  type: string
                  example: http://localhost:8080/profile/staff
        page:
          type: object
          properties:
            size:
              type: integer
              format: int32
              example: 2
            totalElements:
              type: integer
              format: int32
              example: 2
            totalPages:
              type: integer
              format: int32
              example: 1
            number:
              type: integer
              format: int32
              example: 0