version: '3.3'

services:

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    networks:
      - cloud
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/project"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=qwerty007"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  database:
    image:
      postgres
    container_name: database
    networks:
      - cloud
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  cloud:

volumes:
  pgdata:
