server.port: 8000

spring:
  liquibase:
    change-log: classpath:changelog/database_changelog.xml
  datasource:
    hikari.maximum-pool-size: 10
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties.hibernate:
      format_sql: true
      jdbc.batch_size: 30
