server.port: 8000

spring:
  liquibase:
    change-log: classpath:changelog/database_changelog.xml
  datasource:
    hikari.maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty007
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties.hibernate:
      format_sql: true
      jdbc.batch_size: 30
